version: '3.8'

services:
  anagnorisis:
    build: .
    container_name: ${CONTAINER_NAME:-anagnorisis-app}
    ports:
      - "127.0.0.1:${EXTERNAL_PORT:-5001}:5001" # Map the external port to the internal port
    volumes:
      - .:/app  # Mount the source code directory
      - ${IMAGES_MODULE_DATA_PATH:-./media/Images}:/app/media/images
      - ${MUSIC_MODULE_DATA_PATH:-./media/Music}:/app/media/music
      - ${TEXT_MODULE_DATA_PATH:-./media/Text}:/app/media/text
      - ${VIDEOS_MODULE_DATA_PATH:-./media/Videos}:/app/media/videos
      - ${PROJECT_CONFIG_FOLDER_PATH:-./project_config}:/app/project_config
    #restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env   
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RUNNING_IN_DOCKER=true
