FROM python:3.10-slim-buster

# Set environment variables
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

WORKDIR /app

# Copy only requirements to leverage caching
COPY requirements.txt /app/
RUN python -m venv .env && \
    . .env/bin/activate && pip install --upgrade pip && \
    pip install --default-timeout=100 -r requirements.txt

# Now copy the rest of the files
COPY . /app

# Expose the port your app runs on
EXPOSE 5001

# Initialize the database
#RUN source .env/bin/activate
ENV PATH="/app/.env/bin:$PATH"
ENV FLASK_APP=app.py

# Run your commands directly in the Dockerfile
#RUN flask --app app init-db
RUN flask db init
RUN flask db migrate
RUN flask db upgrade
CMD flask run --host=0.0.0.0 --port=5001
